CC = g++
OPTIMIZE = -O2 -std=c++23 -DYAML_CPP_STATIC_DEFINE

OBJ_DIR = ./bin/
SRC_DIR = ./src/

OBJSF = .o
CSF   = .c
CPPSF = .cpp
HSF   = .h
HPPSF = .hpp

TARGET = SAS

# -----------------------------------------------------------------------------------------------------------------------------
#
# App Object
#
# -----------------------------------------------------------------------------------------------------------------------------

MAIN_NAME = App
MAIN_SRC  = $(SRC_DIR)$(MAIN_NAME)$(CPPSF)
MAIN_HDR  = $(SRC_DIR)$(MAIN_NAME)$(HPPSF)
MAIN_OBJ  = $(OBJ_DIR)$(MAIN_NAME)$(OBJSF)

# -----------------------------------------------------------------------------------------------------------------------------
#
# Core Object
#
# -----------------------------------------------------------------------------------------------------------------------------

CORE_DIR  = Core/
CORE_NAME = SasCore
CORE_SRC  = $(SRC_DIR)$(CORE_DIR)$(CORE_NAME)$(CPPSF)
CORE_HDR  = $(SRC_DIR)$(CORE_DIR)$(CORE_NAME)$(HPPSF)
CORE_OBJ  = $(OBJ_DIR)$(CORE_DIR)$(CORE_NAME)$(OBJSF)


# -----------------------------------------------------------------------------------------------------------------------------
#
# Type Object
#
# -----------------------------------------------------------------------------------------------------------------------------
TYPE_DIR  = Type/
# -----------------------------------------------------------------------------------------------------------------------------
ENUM_DIR  = Enum/
# -----------------------------------------------------------------------------------------------------------------------------
ENUM_NAME1 = TypeEnumRole
ENUM_SRC1  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME1)$(CPPSF)
ENUM_HDR1  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME1)$(HPPSF)
ENUM_OBJ1  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME1)$(OBJSF)

ENUM_NAME2 = TypeEnumErogenousZone
ENUM_SRC2  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME2)$(CPPSF)
ENUM_HDR2  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME2)$(HPPSF)
ENUM_OBJ2  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME2)$(OBJSF)

ENUM_NAME3 = TypeEnumSex
ENUM_SRC3  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME3)$(CPPSF)
ENUM_HDR3  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME3)$(HPPSF)
ENUM_OBJ3  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME3)$(OBJSF)

ENUM_NAME4 = TypeEnumColor
ENUM_SRC4  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME4)$(CPPSF)
ENUM_HDR4  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME4)$(HPPSF)
ENUM_OBJ4  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(ENUM_NAME4)$(OBJSF)
# -----------------------------------------------------------------------------------------------------------------------------
ENUM_OBJ  = $(ENUM_OBJ1) $(ENUM_OBJ2) $(ENUM_OBJ3) $(ENUM_OBJ4)
# -----------------------------------------------------------------------------------------------------------------------------
CLOTH_DIR = Cloth/
# -----------------------------------------------------------------------------------------------------------------------------
CLOTH_NAME1 = TypeEnumClothPanty
CLOTH_SRC1  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME1)$(CPPSF)
CLOTH_HDR1  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME1)$(HPPSF)
CLOTH_OBJ1  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME1)$(OBJSF)

CLOTH_NAME2 = TypeEnumClothHairStyle
CLOTH_SRC2  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME2)$(CPPSF)
CLOTH_HDR2  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME2)$(HPPSF)
CLOTH_OBJ2  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME2)$(OBJSF)

CLOTH_NAME3 = TypeEnumClothHeadAccessory
CLOTH_SRC3  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME3)$(CPPSF)
CLOTH_HDR3  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME3)$(HPPSF)
CLOTH_OBJ3  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME3)$(OBJSF)

CLOTH_NAME4 = TypeEnumClothFaceAccessory
CLOTH_SRC4  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME4)$(CPPSF)
CLOTH_HDR4  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME4)$(HPPSF)
CLOTH_OBJ4  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME4)$(OBJSF)

CLOTH_NAME5 = TypeEnumClothEarring
CLOTH_SRC5  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME5)$(CPPSF)
CLOTH_HDR5  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME5)$(HPPSF)
CLOTH_OBJ5  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME5)$(OBJSF)

CLOTH_NAME6 = TypeEnumClothNippleAccessory
CLOTH_SRC6  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME6)$(CPPSF)
CLOTH_HDR6  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME6)$(HPPSF)
CLOTH_OBJ6  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME6)$(OBJSF)

CLOTH_NAME7 = TypeEnumClothNavelAccessory
CLOTH_SRC7  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME7)$(CPPSF)
CLOTH_HDR7  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME7)$(HPPSF)
CLOTH_OBJ7  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME7)$(OBJSF)

CLOTH_NAME8 = TypeEnumClothClitorisAccessory
CLOTH_SRC8  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME8)$(CPPSF)
CLOTH_HDR8  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME8)$(HPPSF)
CLOTH_OBJ8  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME8)$(OBJSF)

CLOTH_NAME9 = TypeEnumClothAnalAccessory
CLOTH_SRC9  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME9)$(CPPSF)
CLOTH_HDR9  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME9)$(HPPSF)
CLOTH_OBJ9  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME9)$(OBJSF)

CLOTH_NAME10 = TypeEnumClothBodyPaint
CLOTH_SRC10  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME10)$(CPPSF)
CLOTH_HDR10  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME10)$(HPPSF)
CLOTH_OBJ10  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME10)$(OBJSF)

CLOTH_NAME11 = TypeEnumClothHandCuffs
CLOTH_SRC11  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME11)$(CPPSF)
CLOTH_HDR11  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME11)$(HPPSF)
CLOTH_OBJ11  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME11)$(OBJSF)

CLOTH_NAME12 = TypeEnumClothWristAccessory
CLOTH_SRC12  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME12)$(CPPSF)
CLOTH_HDR12  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME12)$(HPPSF)
CLOTH_OBJ12  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME12)$(OBJSF)

CLOTH_NAME13 = TypeEnumClothUpperThigh
CLOTH_SRC13  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME13)$(CPPSF)
CLOTH_HDR13  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME13)$(HPPSF)
CLOTH_OBJ13  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME13)$(OBJSF)

CLOTH_NAME14 = TypeEnumClothLegwear
CLOTH_SRC14  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME14)$(CPPSF)
CLOTH_HDR14  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME14)$(HPPSF)
CLOTH_OBJ14  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME14)$(OBJSF)

CLOTH_NAME15 = TypeEnumClothFootwear
CLOTH_SRC15  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME15)$(CPPSF)
CLOTH_HDR15  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME15)$(HPPSF)
CLOTH_OBJ15  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME15)$(OBJSF)

CLOTH_NAME16 = TypeEnumClothNeckAccessory
CLOTH_SRC16  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME16)$(CPPSF)
CLOTH_HDR16  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME16)$(HPPSF)
CLOTH_OBJ16  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME16)$(OBJSF)

CLOTH_NAME17 = TypeEnumClothWaistAccessory
CLOTH_SRC17  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME17)$(CPPSF)
CLOTH_HDR17  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME17)$(HPPSF)
CLOTH_OBJ17  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME17)$(OBJSF)

CLOTH_NAME18 = TypeEnumClothOtherAccessory
CLOTH_SRC18  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME18)$(CPPSF)
CLOTH_HDR18  = $(SRC_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME18)$(HPPSF)
CLOTH_OBJ18  = $(OBJ_DIR)$(TYPE_DIR)$(ENUM_DIR)$(CLOTH_DIR)$(CLOTH_NAME18)$(OBJSF)
# -----------------------------------------------------------------------------------------------------------------------------
CLOTH_OBJ   = $(CLOTH_OBJ1) $(CLOTH_OBJ2) $(CLOTH_OBJ3) $(CLOTH_OBJ4) $(CLOTH_OBJ5)
CLOTH_OBJ  += $(CLOTH_OBJ6) $(CLOTH_OBJ7) $(CLOTH_OBJ8) $(CLOTH_OBJ9) $(CLOTH_OBJ10)
CLOTH_OBJ  += $(CLOTH_OBJ11) $(CLOTH_OBJ12) $(CLOTH_OBJ13) $(CLOTH_OBJ14) $(CLOTH_OBJ15)
CLOTH_OBJ  += $(CLOTH_OBJ16) $(CLOTH_OBJ17) $(CLOTH_OBJ18)
# -----------------------------------------------------------------------------------------------------------------------------
STRUCT_DIR = Struct/
# -----------------------------------------------------------------------------------------------------------------------------
STRUCT_NAME1 = TypeStructErogenousZone
STRUCT_SRC1  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME1)$(CPPSF)
STRUCT_HDR1  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME1)$(HPPSF)
STRUCT_OBJ1  = $(OBJ_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME1)$(OBJSF)

STRUCT_NAME2 = TypeStructConfigAndroidData
STRUCT_SRC2  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME2)$(CPPSF)
STRUCT_HDR2  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME2)$(HPPSF)
STRUCT_OBJ2  = $(OBJ_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME2)$(OBJSF)

STRUCT_NAME3 = TypeStructColor
STRUCT_SRC3  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME3)$(CPPSF)
STRUCT_HDR3  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME3)$(HPPSF)
STRUCT_OBJ3  = $(OBJ_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME3)$(OBJSF)

STRUCT_NAME4 = TypeStructCharacterClothes
STRUCT_SRC4  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME4)$(CPPSF)
STRUCT_HDR4  = $(SRC_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME4)$(HPPSF)
STRUCT_OBJ4  = $(OBJ_DIR)$(TYPE_DIR)$(STRUCT_DIR)$(STRUCT_NAME4)$(OBJSF)
# -----------------------------------------------------------------------------------------------------------------------------
STRUCT_OBJ = $(STRUCT_OBJ1) $(STRUCT_OBJ2) $(STRUCT_OBJ3) $(STRUCT_OBJ4)
# -----------------------------------------------------------------------------------------------------------------------------
TYPES_DIR = Types/
# -----------------------------------------------------------------------------------------------------------------------------
TYPES_NAME1 = TypesUsingTensor
TYPES_SRC1  = $(SRC_DIR)$(TYPE_DIR)$(TYPES_DIR)$(TYPES_NAME1)$(CPPSF)
TYPES_HDR1  = $(SRC_DIR)$(TYPE_DIR)$(TYPES_DIR)$(TYPES_NAME1)$(HPPSF)
TYPES_OBJ1  = $(OBJ_DIR)$(TYPE_DIR)$(TYPES_DIR)$(TYPES_NAME1)$(OBJSF)
# -----------------------------------------------------------------------------------------------------------------------------
TYPES_OBJ = $(TYPES_OBJ1)
# -----------------------------------------------------------------------------------------------------------------------------
WRAPPER_DIR = Wrapper/
# -----------------------------------------------------------------------------------------------------------------------------
WRAPPER_NAME1 = TypeAndroid
WRAPPER_SRC1  = $(SRC_DIR)$(TYPE_DIR)$(WRAPPER_DIR)$(WRAPPER_NAME1)$(CPPSF)
WRAPPER_HDR1  = $(SRC_DIR)$(TYPE_DIR)$(WRAPPER_DIR)$(WRAPPER_NAME1)$(HPPSF)
WRAPPER_OBJ1  = $(OBJ_DIR)$(TYPE_DIR)$(WRAPPER_DIR)$(WRAPPER_NAME1)$(OBJSF)

WRAPPER_NAME2 = TypePersonalityTensor
WRAPPER_SRC2  = $(SRC_DIR)$(TYPE_DIR)$(WRAPPER_DIR)$(WRAPPER_NAME2)$(CPPSF)
WRAPPER_HDR2  = $(SRC_DIR)$(TYPE_DIR)$(WRAPPER_DIR)$(WRAPPER_NAME2)$(HPPSF)
WRAPPER_OBJ2  = $(OBJ_DIR)$(TYPE_DIR)$(WRAPPER_DIR)$(WRAPPER_NAME2)$(OBJSF)
# -----------------------------------------------------------------------------------------------------------------------------
WRAPPER_OBJ = $(WRAPPER_OBJ1) $(WRAPPER_OBJ2)
# -----------------------------------------------------------------------------------------------------------------------------
# All Types Object
# -----------------------------------------------------------------------------------------------------------------------------
TYPE_OBJ = $(ENUM_OBJ) $(CLOTH_OBJ) $(STRUCT_OBJ) $(TYPES_OBJ) $(WRAPPER_OBJ)
# -----------------------------------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------------------------------
#
# All Object
#
# -----------------------------------------------------------------------------------------------------------------------------
OBJ = $(MAIN_OBJ) $(CORE_OBJ) $(TYPE_OBJ)

# -----------------------------------------------------------------------------------------------------------------------------
#
# Rule
#
# -----------------------------------------------------------------------------------------------------------------------------
.PHONY: all
all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OPTIMIZE) -o $(TARGET) $(OBJ)

# -----------------------------------------------------------------------------------------------------------------------------
#
# App Object
#
# -----------------------------------------------------------------------------------------------------------------------------
$(MAIN_OBJ): $(MAIN_SRC) $(MAIN_HDR)
	$(CC) $(OPTIMIZE) -c $(MAIN_SRC) -o $(MAIN_OBJ)

# -----------------------------------------------------------------------------------------------------------------------------
#
# Core Object
#
# -----------------------------------------------------------------------------------------------------------------------------
$(CORE_OBJ): $(CORE_SRC) $(CORE_HDR)
	$(CC) $(OPTIMIZE) -c $(CORE_SRC) -o $(CORE_OBJ)

# -----------------------------------------------------------------------------------------------------------------------------
#
# Type Object
#
# -----------------------------------------------------------------------------------------------------------------------------
# Type / Enum Object
# -----------------------------------------------------------------------------------------------------------------------------
$(ENUM_OBJ1): $(ENUM_SRC1) $(ENUM_HDR1)
	$(CC) $(OPTIMIZE) -c $(ENUM_SRC1) -o $(ENUM_OBJ1)

$(ENUM_OBJ2): $(ENUM_SRC2) $(ENUM_HDR2)
	$(CC) $(OPTIMIZE) -c $(ENUM_SRC2) -o $(ENUM_OBJ2)

$(ENUM_OBJ3): $(ENUM_SRC3) $(ENUM_HDR3)
	$(CC) $(OPTIMIZE) -c $(ENUM_SRC3) -o $(ENUM_OBJ3)

$(ENUM_OBJ4): $(ENUM_SRC4) $(ENUM_HDR4)
	$(CC) $(OPTIMIZE) -c $(ENUM_SRC4) -o $(ENUM_OBJ4)
# -----------------------------------------------------------------------------------------------------------------------------
# Type / Enum / Cloth Object
# -----------------------------------------------------------------------------------------------------------------------------
$(CLOTH_OBJ1): $(CLOTH_SRC1) $(CLOTH_HDR1)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC1) -o $(CLOTH_OBJ1)
	
$(CLOTH_OBJ2): $(CLOTH_SRC2) $(CLOTH_HDR2)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC2) -o $(CLOTH_OBJ2)

$(CLOTH_OBJ3): $(CLOTH_SRC3) $(CLOTH_HDR3)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC3) -o $(CLOTH_OBJ3)

$(CLOTH_OBJ4): $(CLOTH_SRC4) $(CLOTH_HDR4)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC4) -o $(CLOTH_OBJ4)

$(CLOTH_OBJ5): $(CLOTH_SRC5) $(CLOTH_HDR5)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC5) -o $(CLOTH_OBJ5)

$(CLOTH_OBJ6): $(CLOTH_SRC6) $(CLOTH_HDR6)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC6) -o $(CLOTH_OBJ6)
	
$(CLOTH_OBJ7): $(CLOTH_SRC7) $(CLOTH_HDR7)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC7) -o $(CLOTH_OBJ7)

$(CLOTH_OBJ8): $(CLOTH_SRC8) $(CLOTH_HDR8)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC8) -o $(CLOTH_OBJ8)

$(CLOTH_OBJ9): $(CLOTH_SRC9) $(CLOTH_HDR9)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC9) -o $(CLOTH_OBJ9)

$(CLOTH_OBJ10): $(CLOTH_SRC10) $(CLOTH_HDR10)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC10) -o $(CLOTH_OBJ10)

$(CLOTH_OBJ11): $(CLOTH_SRC11) $(CLOTH_HDR11)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC11) -o $(CLOTH_OBJ11)
	
$(CLOTH_OBJ12): $(CLOTH_SRC12) $(CLOTH_HDR12)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC12) -o $(CLOTH_OBJ12)

$(CLOTH_OBJ13): $(CLOTH_SRC13) $(CLOTH_HDR13)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC13) -o $(CLOTH_OBJ13)

$(CLOTH_OBJ14): $(CLOTH_SRC14) $(CLOTH_HDR14)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC14) -o $(CLOTH_OBJ14)

$(CLOTH_OBJ15): $(CLOTH_SRC15) $(CLOTH_HDR15)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC15) -o $(CLOTH_OBJ15)

$(CLOTH_OBJ16): $(CLOTH_SRC16) $(CLOTH_HDR16)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC16) -o $(CLOTH_OBJ16)

$(CLOTH_OBJ17): $(CLOTH_SRC17) $(CLOTH_HDR17)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC17) -o $(CLOTH_OBJ17)

$(CLOTH_OBJ18): $(CLOTH_SRC18) $(CLOTH_HDR18)
	$(CC) $(OPTIMIZE) -c $(CLOTH_SRC18) -o $(CLOTH_OBJ18)
# -----------------------------------------------------------------------------------------------------------------------------
# Type / Struct Object
# -----------------------------------------------------------------------------------------------------------------------------
$(STRUCT_OBJ1): $(STRUCT_SRC1) $(STRUCT_HDR1)
	$(CC) $(OPTIMIZE) -c $(STRUCT_SRC1) -o $(STRUCT_OBJ1)

$(STRUCT_OBJ2): $(STRUCT_SRC2) $(STRUCT_HDR2)
	$(CC) $(OPTIMIZE) -c $(STRUCT_SRC2) -o $(STRUCT_OBJ2)

$(STRUCT_OBJ3): $(STRUCT_SRC3) $(STRUCT_HDR3)
	$(CC) $(OPTIMIZE) -c $(STRUCT_SRC3) -o $(STRUCT_OBJ3)

$(STRUCT_OBJ4): $(STRUCT_SRC4) $(STRUCT_HDR4)
	$(CC) $(OPTIMIZE) -c $(STRUCT_SRC4) -o $(STRUCT_OBJ4)
# -----------------------------------------------------------------------------------------------------------------------------
# Type / Types Object
# -----------------------------------------------------------------------------------------------------------------------------
$(TYPES_OBJ1): $(TYPES_SRC1) $(TYPES_HDR1)
	$(CC) $(OPTIMIZE) -c $(TYPES_SRC1) -o $(TYPES_OBJ1)
# -----------------------------------------------------------------------------------------------------------------------------
# Type / Wrapper Object
# -----------------------------------------------------------------------------------------------------------------------------
$(WRAPPER_OBJ1): $(WRAPPER_SRC1) $(WRAPPER_HDR1)
	$(CC) $(OPTIMIZE) -c $(WRAPPER_SRC1) -o $(WRAPPER_OBJ1)

$(WRAPPER_OBJ2): $(WRAPPER_SRC2) $(WRAPPER_HDR2)
	$(CC) $(OPTIMIZE) -c $(WRAPPER_SRC2) -o $(WRAPPER_OBJ2)
# -----------------------------------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------------------------------